version: "3"

services:
  alice:
    build: .
    ports:
      - "8001:8008"
    volumes:
      - "./dev:/code/dev"
      - "./out:/code/out"
      - "./src:/code/src"
      - "data-alice:/root/.ssb"
  bob:
    build: .
    ports:
      - "8002:8008"
    volumes:
      - "./dev:/code/dev"
      - "./out:/code/out"
      - "./src:/code/src"
      - "data-bob:/root/.ssb"

volumes:
  data-alice:
  data-bob:
