# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022

# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

sbot-do () {
  sbot $@ -- --caps.shs=$SBOT_SHS --caps.sign=$SBOT_SIGN
}

sbot-bg () {
  sbot $@ -- --caps.shs=$SBOT_SHS --caps.sign=$SBOT_SIGN &
}
